### ISSUE TITLE
After first time install on Ubuntu 20.04 I get an error during the sync

### ISSUE THREAD

**Issue by placson** [wasta-linux/logos9-snap#1]
First of all, thank you for this project!  I'm a big Logos user and boot Windows and Ubuntu constantly to get my work done. If I could stay in Ubuntu that would be fantastic. I tried your installer for the first time and the install went fine but the moment I tried to login with my account it did the sync and I got this exception (with debugging enabled):

01e0:fixme:advapi:ReportEventW (00000000CAFE4242,0x0001,0x0000,0x00000402,0000000000000000,0x0001,0x00000000,0000000047F3AC30,0000000000000000): stub
01e0:err:eventlog:ReportEventW L"Application: Logos.exe\nFramework Version: v4.0.30319\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.AccessViolationException\n   at System.Net.UnsafeNclNativeMethods+OSSOCK.select(Int32, IntPtr[], IntPtr[], IntPtr[], System.Net.Sockets.Tim"...
01e0:fixme:advapi:DeregisterEventSource (00000000CAFE4242) stub

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other mem
ory is corrupt.
   at System.Net.UnsafeNclNativeMethods.OSSOCK.select(Int32 ignoredParameter, IntPtr[] readfds, IntPtr[] writefds, IntPtr[] exceptfds, TimeVa
lue& timeout)
   at System.Net.Sockets.Socket.Poll(Int32 microSeconds, SelectMode mode)
   at System.Net.Connection.IsConnectionReusable()
   at System.Net.Connection.StartRequest(HttpWebRequest request, Boolean canPollRead)
   at System.Net.Connection.SubmitRequest(HttpWebRequest request, Boolean forcedsubmit)
   at System.Net.ServicePoint.SubmitRequest(HttpWebRequest request, String connName)
   at System.Net.HttpWebRequest.SubmitRequest(ServicePoint servicePoint)
   at System.Net.HttpWebRequest.GetResponse()
   at Libronix.Utility.Net.HttpWebRequestUtility.DoGetHttpResponse(Func`1 fnGetResponse)
   at Libronix.DigitalLibrary.UpdateUtility.GetDownloadSize(IHttpWebRequestFactory webRequestFactory, IEnumerable`1 seqUris)
   at Libronix.DigitalLibrary.UpdateManager.<CheckForResourcePatches>b__58_3(UriSize x)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preser
veSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCt
x)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
wine: Unhandled page fault on read access to 0000000004C2A000 at address 000000006D58E81C (thread 01e0), starting debugger...
01f0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01f0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01f0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01f0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
01fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.

Any suggestions on w to fix would be appreciated!  Thank you.

**Comment by placson** [comment]
I read the readme and tried this shell and it seems to be working

# Enter logos9's shell.
snap run --shell logos9
# Run Logos.exe via sommelier script.
WINEDLLOVERRIDES= sommelier run-exe

Starting logos from the shell seems to work and is currently downloading my 4GB's worth of libraries.

So far so good!

**Comment by placson** [comment]
Looks like this is also failing 

`$ [0204/164950.538:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[0204/164950.942:ERROR:dxva_video_decode_accelerator_win.cc(1368)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not fo
und. (0x7E)
[0204/164951.037:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other mem
ory is corrupt.
   at MS.Win32.PresentationCore.UnsafeNativeMethods.MILUnknown.Release(IntPtr pIUnkown)
   at MS.Win32.PresentationCore.UnsafeNativeMethods.MILUnknown.ReleaseInterface(IntPtr& ptr)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& cls
Id, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions
, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at Libronix.Utility.Windows.BitmapSourceUtility.EndInitHandlingDecodeFailure[TBitmapSource](TBitmapSource image)
   at Libronix.Utility.Windows.BitmapSourceUtility.<>c__DisplayClass7_0.<CreateFromStream>b__0()
   at Libronix.Utility.Windows.BitmapSourceUtility.NullIfFailedCreation[T](Func`1 fn, Exception& exception)
   at Libronix.Utility.Windows.BitmapSourceUtility.CreateFromStream(Stream stream, Int32 nDecodePixelWidth, Int32 nDecodePixelHeight)
   at Libronix.Utility.Windows.BitmapSourceUtility.CreateFromByteArray(Byte[] aby)
   at LDLS4.NotificationsViewModel.CreateResourceUpdatePopupMessage(ResourceInfo resourceInfo, Boolean showImage, CancellationToken cancellat
ionToken)
   at LDLS4.NotificationsViewModel.<>c__DisplayClass46_0.<RefreshResourceUpdatesNotification>b__3(ResourceInfo x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at LDLS4.NotificationsViewModel.<RefreshResourceUpdatesNotification>d__46.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preser
veSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCt
x)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHand
ler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preser
veSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCt
x)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object 
state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHand
ler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32
 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at LDLS4.OurApp.InitializeAndRun(ReadOnlyCollection`1 listArgs, SingleInstanceManager sim, Scope telemetryStep)
   at LDLS4.OurApp.Main(String[] astrArgs)
wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 01f0), starting debugger...
`
